version: "3"
services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/db
      - EOS_URL=https://eos.greymass.com/v1/history/get_actions
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
